package com.changas.model.status;

public enum TransactionStatus {
    AWAITING_PROVIDER_CONFIRMATION,
    AWAITING_REQUESTER_CONFIRMATION,
    DECLINED_BY_PROVIDER,
    DECLINED_BY_REQUESTER,
    ACCEPTED_BY_REQUESTER

}
