name: CI Workflow

on:
  push:
    branches: ["master", "feature/*", "fix/*", "refactor/*"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Firestore Credentials
        run: |
            echo "${{ secrets.FIRESTORE_CREDENTIALS }}" | base64 --decode > $HOME/firestore-credentials.json
            echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firestore-credentials.json" >> $GITHUB_ENV
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build -x test
